config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#index'
  resources :users, :cars, :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user

  enum specie: %i[perro gato pájaro]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cars, dependent: :destroy
  has_many :pets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]
  before_action :set_users

  def index
    @cars = Car.all
  end

  def show; end

  def new
    @car = Car.new
  end

  def edit; end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to cars_path
    else
      render :new
    end
  end

  def update
    if @car.update(car_params)
      redirect_to cars_path
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def set_users
    @users = User.all.pluck(:first_name, :id)
  end

  def car_params
    params.require(:car).permit(:color, :doors_amount, :brand, :user_id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index; end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[show edit update destroy]
  before_action :set_users

  def index
    @pets = Pet.all
  end

  def show; end

  def new
    @pet = Pet.new
  end

  def edit; end

  def create
    @pet = Pet.new(pet_params)

    if @pet.save
      redirect_to pets_path
    else
      render :new
    end
  end

  def update
    if @pet.update(pet_params)
      redirect_to pets_path
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def set_users
    @users = User.all.pluck(:first_name, :id)
  end

  def pet_params
    params.require(:pet).permit(:name, :specie, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pet_species
    Pet.species.keys.map do |specie|
      [specie, specie]
    end
  end
end

app/views/cars/_form.html.haml
= form_for @car, validate: true do |f|
  .form-group
    = f.label "Color", class: 'form-label required'
    = f.text_field :color, autofocus: true, class: 'form-control'
  .form-group
    = f.label "Cantidad de puertas", class: 'form-label required'
    = f.text_field :doors_amount, autofocus: true, class: 'form-control', type: :number
  .form-group
    = f.label "Marca", class: 'form-label required'
    = f.text_field :brand, autofocus: true, class: 'form-control'
  .form-group
    = f.label "Dueño", class: 'form-label required'
    = f.select(:user_id, options_for_select(@users, @car.user),
                        {prompt:"Seleccione"}, class:'form-control')
  .row
    .offset-3.col-3
      = link_to "Atrás", cars_path,  class: 'btn btn-secondary btn-block'
    .col-3
      = button_tag "Guardar", class: 'btn btn-outline-success btn-block',
          'data-disable-with': "Guardando..."

app/views/cars/edit.html.haml
.page-header
  %h1= "Editar Usuario"

= render 'form'

app/views/cars/index.html.haml
.page-header
  %h1.mb-4
    ="Listado de carros"
    .float-right
      = link_to "Nuevo carro", new_car_path, class: 'btn btn-primary'

%table.table.table-striped
  %thead
    %tr
      %th="Color"
      %th="Cantodad de puertas"
      %th="Marca"
      %th="Dueño"
      %th
      %th
      %th

  %tbody
    - @cars.each do |car|
      %tr
        %td= car.color
        %td= car.doors_amount
        %td= car.brand
        %td= car.user.first_name
        %td= link_to "Ver", car, class: 'btn btn-info'
        %td= link_to "Editar", edit_car_path(car), class: 'btn btn-success'
        %td= link_to "Eliminar", car, method: :delete, class: 'btn btn-danger',
                  data: { confirm: "Desea eliminarlo",
                    accept: "OK",
                    reject: "CANCELAR" }

%br

app/views/cars/new.html.haml
.page-header
  %h1.mb-4
    = "Nuevo Usuario"
= render 'form'

app/views/cars/show.html.haml
%p#notice= notice
.card
  .card-body
    %h5.card-title color:
    %p.card-text &nbsp #{ @car.color }
    %h5.card-title Cantidad de puertas:
    %p.card-text &nbsp #{ @car.doors_amount }
    %h5.card-title Marca:
    %p.card-text &nbsp #{ @car.brand }

.row.mt-3
  .col-3
    = link_to "Atrás", cars_path,  class: 'btn btn-secondary btn-block'

app/views/dashboards/index.html.haml
%h1.mb-4
  ="CRUDs disponibles"
.float-left
  = link_to "Usuario", users_path, class: 'btn btn-primary'
.float-left
  = link_to "Carro", cars_path, class: 'btn btn-primary'
.float-left
  = link_to "Mascota", pets_path, class: 'btn btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.haml
= form_for @pet, validate: true do |f|
  .form-group
    = f.label "Nombre", class: 'form-label required'
    = f.text_field :name, autofocus: true, class: 'form-control'
  .form-group
    = f.label "Tipo", class: 'form-label required'
    = f.select(:specie, options_for_select(pet_species, @pet.specie),
                        {prompt:"Seleccione"}, class:'form-control')
  .form-group
    = f.label "Dueño", class: 'form-label required'
    = f.select(:user_id, options_for_select(@users, @pet.user),
                        {prompt:"Seleccione"}, class:'form-control')
  .row
    .offset-3.col-3
      = link_to "Atrás", pets_path,  class: 'btn btn-secondary btn-block'
    .col-3
      = button_tag "Guardar", class: 'btn btn-outline-success btn-block',
          'data-disable-with': "Guardando..."

app/views/pets/edit.html.haml
.page-header
  %h1= "Editar Mascota"

= render 'form'

app/views/pets/index.html.haml
.page-header
  %h1.mb-4
    ="Listado de mascotas"
    .float-right
      = link_to "Nueva mascota", new_pet_path, class: 'btn btn-primary'

%table.table.table-striped
  %thead
    %tr
      %th="Nombre"
      %th="Tipo"
      %th="Dueño"
      %th
      %th
      %th

  %tbody
    - @pets.each do |pet|
      %tr
        %td= pet.name
        %td= pet.specie
        %td= pet.user.first_name
        %td= link_to "Ver", pet, class: 'btn btn-info'
        %td= link_to "Editar", edit_pet_path(pet), class: 'btn btn-success'
        %td= link_to "Eliminar", pet, method: :delete, class: 'btn btn-danger',
                  data: { confirm: "Desea eliminarlo",
                    accept: "OK",
                    reject: "CANCELAR" }

%br

app/views/pets/new.html.haml
.page-header
  %h1.mb-4
    = "Nuevo Usuario"
= render 'form'

app/views/pets/show.html.haml
%p#notice= notice
.card
  .card-body
    %h5.card-title Nombre:
    %p.card-text &nbsp #{ @pet.name }
    %h5.card-title Tipo:
    %p.card-text &nbsp #{ @pet.specie }
    %h5.card-title Dueño:
    %p.card-text &nbsp #{ @pet.user.first_name }

.row.mt-3
  .col-3
    = link_to "Atrás", pets_path,  class: 'btn btn-secondary btn-block'

app/views/users/_form.html.haml
= form_for @user, validate: true do |f|
  .form-group
    = f.label "Nombre", class: 'form-label required'
    = f.text_field :first_name, autofocus: true, class: 'form-control'
  .form-group
    = f.label "Apellido", class: 'form-label required'
    = f.text_field :last_name, autofocus: true, class: 'form-control'
  .row
    .offset-3.col-3
      = link_to "Atrás", users_path,  class: 'btn btn-secondary btn-block'
    .col-3
      = button_tag "Guardar", class: 'btn btn-outline-success btn-block',
          'data-disable-with': "Guardando..."

app/views/users/edit.html.haml
.page-header
  %h1= "Editar Usuario"

= render 'form'

app/views/users/index.html.haml
.page-header
  %h1.mb-4
    ="Listado de usuarios"
    .float-right
      = link_to "Nuevo usuario", new_user_path, class: 'btn btn-primary'

%table.table.table-striped
  %thead
    %tr
      %th="Nombre"
      %th="Apellido"
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.first_name
        %td= user.last_name
        %td= link_to "Ver", user, class: 'btn btn-info'
        %td= link_to "Editar", edit_user_path(user), class: 'btn btn-success'
        %td= link_to "Eliminar", user, method: :delete, class: 'btn btn-danger',
                  data: { confirm: "Desea eliminarlo",
                    accept: "OK",
                    reject: "CANCELAR" }

%br

app/views/users/new.html.haml
.page-header
  %h1.mb-4
    = "Nuevo Usuario"
= render 'form'

app/views/users/show.html.haml
%p#notice= notice
.card
  .card-body
    %h5.card-title Nombre:
    %p.card-text &nbsp #{ @user.first_name }
    %h5.card-title Apellido:
    %p.card-text &nbsp #{ @user.last_name }

.row.mt-3
  .col-3
    = link_to "Atrás", users_path,  class: 'btn btn-secondary btn-block'